pywren: 
    storage_bucket: <BUCKET_NAME>
    #storage_prefix: pywren.jobs
    storage_backend: azure_blob
    compute_backend: azure_fa
    #rabbitmq_monitor: <True/False>
    #data_cleaner: <True/False>
    #runtime :
    #runtime_timeout: 600000     # Default timeout
    #runtime_memory: 256         # Default memory
    #invocation_retry: <True/False>
    #retry_sleeps: [1, 5, 10, 20, 30]
    #retries: 5

#ibm:
#    iam_api_key: <IAM KEY>

#ibm_cf:
    #endpoint    : <REGION_ENDPOINT>
    #namespace   : <NAMESPACE>
    #api_key     : <API_KEY>

#ibm_cos:
    #endpoint   : <REGION_ENDPOINT>
    #api_key    : <API_KEY>
    #access_key : <ACCESS_KEY>  # Optional
    #secret_key : <SECRET_KEY>  # Optional
    
#swift:
    #auth_url   : <SWIFT_AUTH_URL>
    #region     : <SWIFT_REGION>
    #user_id    : <SWIFT_USER_ID>
    #project_id : <SWIFT_PROJECT_ID>
    #password   : <SWIFT_PASSWORD>

azure_blob:
    account_name : <AZURE_STORAGE_ACCOUNT_NAME>
    account_key  : <AZURE_STORAGE_ACCOUNT_KEY>

azure_fa:
    resource_group: <AZURE_RESOURCE_GROUP>
    service_plan: <AZURE_SERVICE_PLAN>
    account_name : <AZURE_STORAGE_ACCOUNT_NAME>
    account_key  : <AZURE_STORAGE_ACCOUNT_KEY>
    docker_username : <DOCKER_USERNAME>

#rabbitmq:
    #amqp_url 	: <RABBIT_AMQP_URL>  # amqp://